# Generated by Django 5.2.5 on 2025-08-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Student',
            new_name='student',
        ),
    ]
